### PR TITLE
fix(metrics)!: hold onto `MetricsProvider` in `MetricsLayer`

### LINKED ISSUE #178: MetricsLayer does not really pipe metrics to reader
## Bug Report
metrics reader never get anything from MetricsLayer

### Version

opentelemetry = { version = "0.26", features = ["trace"] }
opentelemetry-proto = { version = "0.26", features = ["trace"] }
opentelemetry_sdk = { version = "0.26", features = ["trace", "rt-tokio"] }
tracing-opentelemetry = "0.27"

### Description

image
image
image
image
image

### PR DESCRIPTION
**Pull request by mladedav**
## Motivation

Fixes #178 

Dropping `MeterProvider` early shuts down the `Meter` we carry aroud forcing users wither to keep a copy of the provider for the duration of their program or losing all their metrics.

## Solution

Keep the provider inside our layer. It adds a new generic argument to the type which is a breaking change.

The tests were written in a way that prevented this bug by having the provider cloned so I've got rid of that too.

### CODE REVIEW

File: src/metrics.rs [hunk 1]
```diff
@@ -467,7 +469,7 @@ where
     }
 }
 
-impl<S> Layer<S> for MetricsLayer<S>
+impl<S, M: 'static> Layer<S> for MetricsLayer<S, M>
```
Comment (djc) [inline src/metrics.rs:472]: Why does this need the explicit lifetime?

**Review by djc — COMMENTED** [review]
This looks like it'll be semver-breaking, maybe include a proactive semver-incompatible version bump?

File: src/metrics.rs (hunk 1 above)
Comment (mladedav) [reply src/metrics.rs:472]: Because `Layer<S>` has a `Self: 'static` clause.

**Comment by mladedav** [comment]
As for the semver incompatible bump, I'm still planning to use `realease-plz` which bumps the version on release so that it's not accidentally bumped multiple times between releases. Since the commits contain conventional commits with an `!` it knows there have been breaking changes.
